# Generated by Django 6.0.1 on 2026-02-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oblast_ocenjivanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tezinski_koeficijent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koef_1', models.DecimalField(decimal_places=3, max_digits=4)),
                ('koef_2', models.DecimalField(decimal_places=3, max_digits=4)),
                ('koef_3', models.DecimalField(decimal_places=3, max_digits=4)),
                ('koef_4', models.DecimalField(decimal_places=3, max_digits=4)),
                ('koef_5', models.DecimalField(decimal_places=3, max_digits=4)),
                ('oblast_ocenjivanja_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeficijent_1', to='ocenjivanje.oblast_ocenjivanja')),
                ('oblast_ocenjivanja_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeficijent_2', to='ocenjivanje.oblast_ocenjivanja')),
                ('oblast_ocenjivanja_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeficijent_3', to='ocenjivanje.oblast_ocenjivanja')),
                ('oblast_ocenjivanja_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeficijent_4', to='ocenjivanje.oblast_ocenjivanja')),
                ('oblast_ocenjivanja_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeficijent_5', to='ocenjivanje.oblast_ocenjivanja')),
                ('orgjedinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.organizaciona_jedinica')),
                ('radno_mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.radno_mesto')),
            ],
            options={
                'verbose_name': 'Težinski koeficijent',
                'verbose_name_plural': 'Težinski koeficijenti',
            },
        ),
        migrations.CreateModel(
            name='Ocena_zaposlenog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena_1', models.IntegerField()),
                ('ocena_2', models.IntegerField()),
                ('ocena_3', models.IntegerField()),
                ('ocena_4', models.IntegerField()),
                ('ocena_5', models.IntegerField()),
                ('zbirna_ocena', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('datum_Od', models.DateField()),
                ('datum_Do', models.DateField()),
                ('rukovodilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocenjivac', to=settings.AUTH_USER_MODEL)),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocene', to=settings.AUTH_USER_MODEL)),
                ('tezinski_koeficijent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocenjivanje.tezinski_koeficijent')),
            ],
        ),
    ]
