# Generated by Django 6.0.1 on 2026-02-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocenjivanje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tezinski_koeficijent',
            name='orgjedinica',
        ),
    ]
