# Generated by Django 6.0.1 on 2026-08-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocenjivanje', '0002_remove_tezinski_koeficijent_orgjedinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocena_zaposlenog',
            options={'ordering': ['-datum_Od'], 'verbose_name': 'Ocena zaposlenog', 'verbose_name_plural': 'Ocene zaposlenih'},
        ),
    ]
