# Generated by Django 6.0.1 on 2026-08-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True, null=True)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Dodeljeni_KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_Od', models.DateField()),
                ('datum_Do', models.DateField()),
                ('datum_dodele', models.DateField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodeljeni_kpi', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodeljeni', to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'Dodeljeni KPI',
                'verbose_name_plural': 'Dodeljeni KPI',
                'ordering': ['-datum_Od'],
                'unique_together': {('kpi', 'korisnik', 'datum_Od', 'datum_Do')},
            },
        ),
        migrations.CreateModel(
            name='Ostvareni_KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostvarena_vrednost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datum', models.DateField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('dodeljeni_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostvareni', to='kpi.dodeljeni_kpi')),
                ('rukovodilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uneti_kpi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ostvareni KPI',
                'verbose_name_plural': 'Ostvareni KPI',
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
