# Generated by Django 6.0.1 on 2026-08-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firma', '0002_organizaciona_jedinica_rukovodilac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('radno_mesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plata', to='firma.radno_mesto')),
            ],
            options={
                'verbose_name': 'Plata',
                'verbose_name_plural': 'Plate',
            },
        ),
        migrations.CreateModel(
            name='Isplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_isplate', models.DateField()),
                ('iznos_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iznos_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('datum_izmene', models.DateTimeField(auto_now=True)),
                ('izmenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izmenjene_isplate', to=settings.AUTH_USER_MODEL)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isplate', to=settings.AUTH_USER_MODEL)),
                ('plata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isplate', to='plate.plata')),
            ],
            options={
                'verbose_name': 'Isplata',
                'verbose_name_plural': 'Isplate',
                'ordering': ['-datum_isplate'],
            },
        ),
    ]
