# Generated by Django 6.0.1 on 2026-01-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('aktivan', 'Aktivan'), ('neaktivan', 'Neaktivan')], default='neaktivan', max_length=20)),
            ],
            options={
                'verbose_name': 'Cilj',
                'verbose_name_plural': 'Ciljevi',
            },
        ),
        migrations.CreateModel(
            name='Tip_cilja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tip cilja',
                'verbose_name_plural': 'Tipovi ciljeva',
            },
        ),
        migrations.CreateModel(
            name='Dodeljeni_cilj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_Od', models.DateField()),
                ('datum_Do', models.DateField()),
                ('cilj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodeljeni_ciljevi', to='ciljevi.cilj')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodeljeni_ciljevi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dodeljeni cilj',
                'verbose_name_plural': 'Dodeljeni ciljevi',
            },
        ),
        migrations.AddField(
            model_name='cilj',
            name='tip_cilja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciljevi', to='ciljevi.tip_cilja'),
        ),
    ]
