# Generated by Django 6.0.1 on 2026-01-30 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciljevi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dodeljeni_cilj',
            unique_together={('cilj', 'zaposleni', 'datum_Od', 'datum_Do')},
        ),
    ]
