# Generated by Django 6.0.1 on 2026-02-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciljevi', '0002_alter_dodeljeni_cilj_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cilj',
            name='naziv',
            field=models.CharField(max_length=100),
        ),
    ]
