# Generated by Django 6.0.1 on 2026-01-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizaciona_jedinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('nadredjena_org_jed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podrejene_org_jedinice', to='firma.organizaciona_jedinica')),
            ],
        ),
        migrations.CreateModel(
            name='Radno_mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('org_jed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radna_mesta', to='firma.organizaciona_jedinica')),
            ],
        ),
    ]
