# Generated by Django 6.0.1 on 2026-08-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_Od', models.DateField()),
                ('datum_Do', models.DateField()),
                ('broj_dana', models.PositiveIntegerField(default=0)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('na_cekanju', 'Na čekanju'), ('odobren', 'Odobren'), ('odbijen', 'Odbijen')], default='na_cekanju', max_length=20)),
                ('razlog_odbijanja', models.TextField(blank=True, null=True)),
                ('datum_podnosenja', models.DateTimeField(auto_now_add=True)),
                ('datum_obrade', models.DateTimeField(blank=True, null=True)),
                ('obradio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obradjeni_odmori', to=settings.AUTH_USER_MODEL)),
                ('rukovodilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odmori_tima', to=settings.AUTH_USER_MODEL)),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odmori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odmor',
                'verbose_name_plural': 'Odmori',
                'ordering': ['-datum_podnosenja'],
            },
        ),
    ]
